"""Vault scaffolding — file/dir templates created when a vault is first set up.

The wizard's "Vault" step calls into :func:`scaffold_vault`. It creates the
standard folder tree and seeds ``vault.yaml``, ``prime.md``, and per-agent
directories. Safe to call against an existing vault — only missing pieces are
written; nothing is overwritten.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

CORE_FOLDERS: tuple[str, ...] = (
    "daily",
    "projects",
    "topics",
    "people",
    "captures",
    ".archive",
)

LOOM_AGENTS: tuple[str, ...] = ("weaver", "spider", "archivist", "scribe", "sentinel")
SHUTTLE_AGENTS: tuple[str, ...] = ("researcher", "standup")

VAULT_YAML_TEMPLATE = """# Vault config — generated by Loom onboarding
name: {name}
created: {created}
folders:
  core: [daily, projects, topics, people, captures]
  custom: []
"""

PRIME_MD_TEMPLATE = """---
title: prime.md — vault constitution
type: rule
created: {created}
modified: {created}
---

# Prime

This document is your vault's constitution. **Loom agents read it before every
write.** They cannot edit it. You can.

## Voice & tone

- Keep notes plain-spoken. Skip filler.
- Default to short paragraphs; lists when listing.

## Linking

- Use `[[wikilinks]]` for any cross-note reference.
- Tag heavily. Tags drive the index.

## What agents are allowed to do

- Weaver: create notes from captures.
- Spider: discover and add wikilinks.
- Archivist: move/archive notes when stale.
- Scribe: summarize on `## Summary` request.
- Sentinel: validate frontmatter, flag policy issues.

Edit this file freely. Restart no required — agents re-read it each cycle.
"""

AGENT_MEMORY_TEMPLATE = """---
agent: {name}
created: {created}
---

# {title} memory

This is the agent's running scratchpad. Auto-summarised every 20 actions.
"""

AGENT_STATE_TEMPLATE = '{{"last_run": null, "action_count": 0}}\n'


def _utcnow() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


def vault_root_for(loom_dir: Path, name: str) -> Path:
    return loom_dir / "vaults" / name


def is_scaffolded(vault_dir: Path) -> bool:
    """A vault is 'scaffolded' once its ``vault.yaml`` exists."""
    return (vault_dir / "vault.yaml").is_file()


def scaffold_vault(vault_dir: Path, name: str) -> None:
    """Create folder tree and seed files. Idempotent: missing pieces only."""
    created = _utcnow()
    vault_dir.mkdir(parents=True, exist_ok=True)

    threads = vault_dir / "threads"
    threads.mkdir(exist_ok=True)
    for folder in CORE_FOLDERS:
        (threads / folder).mkdir(exist_ok=True)

    agents = vault_dir / "agents"
    agents.mkdir(exist_ok=True)
    for agent in (*LOOM_AGENTS, *SHUTTLE_AGENTS):
        agent_dir = agents / agent
        agent_dir.mkdir(exist_ok=True)
        (agent_dir / "logs").mkdir(exist_ok=True)
        memory_file = agent_dir / "memory.md"
        if not memory_file.exists():
            memory_file.write_text(
                AGENT_MEMORY_TEMPLATE.format(name=agent, title=agent.capitalize(), created=created),
                encoding="utf-8",
            )
        state_file = agent_dir / "state.json"
        if not state_file.exists():
            state_file.write_text(AGENT_STATE_TEMPLATE, encoding="utf-8")
    for shuttle in SHUTTLE_AGENTS:
        (agents / shuttle / "chat").mkdir(exist_ok=True)
    council_chat = agents / "_council" / "chat"
    council_chat.mkdir(parents=True, exist_ok=True)

    rules = vault_dir / "rules"
    rules.mkdir(exist_ok=True)
    for sub in ("schemas", "policies", "workflows"):
        (rules / sub).mkdir(exist_ok=True)
    prime = rules / "prime.md"
    if not prime.exists():
        prime.write_text(PRIME_MD_TEMPLATE.format(created=created), encoding="utf-8")

    prompts = vault_dir / "prompts"
    prompts.mkdir(exist_ok=True)
    (prompts / "shared").mkdir(exist_ok=True)

    loom_meta = vault_dir / ".loom"
    loom_meta.mkdir(exist_ok=True)
    (loom_meta / "changelog").mkdir(exist_ok=True)

    vault_yaml = vault_dir / "vault.yaml"
    if not vault_yaml.exists():
        vault_yaml.write_text(
            VAULT_YAML_TEMPLATE.format(name=name, created=created),
            encoding="utf-8",
        )
